### ISSUE TITLE
Peer review: Commenting on code

### ISSUE THREAD

**Issue by ayaderaghul** [fuadmoin/Portfolio#9]
- Your portfolio looks very good and professional in both desktop and mobile version.
- In the index.html there are some space lines that can be removed so that the file structure looks more formatted.

**Comment by baqar-abbas** [comment]
Hi Fuad , I would like to acknowledge the nice effort that you put in to make it a perfectly working Responsive Design. As per part of further improvements I think I would agree with ayederaghul that you can remove some extra spacing and proper indentation would help you organize your code much better. Keep up the good work.
